name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - uses: actions/checkout@v3

      - name: vcpkg plan
        run: vcpkg install --dry-run --x-json > vcpkg.plan

      - uses: actions/cache@v3
        with:
          path: ~/.cache/vcpkg
          key: vcpkg-${{ hashFiles('vcpkg.plan') }}

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build

      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          assets=(build/mkpfs build/ast_checker)
          for rel in $(gh release list | awk -F'\t' '{print$3}')
          do
            gh release delete $rel -y
          done
          git ls-remote --tags | awk '{print$2}' | xargs git push --delete origin || true
          gh release create latest "${assets[@]}" -t "Latest Release"